### ISSUE TITLE
Question about export the trained 3D pore structure image as the stl format

### ISSUE THREAD

**Issue by hailangsy** [stke9/SliceGAN#15]
Hello，it's really a wonderful work.  Could I ask how to save the trained 3D pore structure image as the stl format in the raytrace.py by optix for the following diffusion simulation. Thank you very much.

**Comment by stke9** [comment]
Hi there,

Thanks for using the software, you are best off using a for purpose meshing tool to go from tiff to STL, for example in fiji. Sorry for the late reply!

**Comment by hailangsy** [comment]
Thank you very much



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/12/2023 16:29 |
| To | ***@***.***> |
| Cc | Lucinda ***@***.***>***@***.***> |
| Subject | Re: [stke9/SliceGAN] Question about export the trained 3D pore structure image as the stl format (Issue #15) |

Closed #15 as completed.
