### ISSUE TITLE
dataset creating memory issue

### ISSUE THREAD

**Issue by oslopanda** [stke9/SliceGAN#9]
Hello stke9,

Thank you for the nice work. I have one issue when running the dataset generation in the preprocessing using one tif image my own. 

when running:
data = np.empty([32 * 900, len(vals), l, l])
i got erroa message that the np core issue, can not allocate 200 G memory for the array (28800, ?, 64, 64)
in data type 'float64' (forget the number of vals)
so my question is what the 32*900 means. i have a GPU with only 5 G memory size, can i change the value to something else?
however, when i use the input image with the NMC.tif in your Example file, i dont get the erroa. what could be the reason for this?

best regards,
OP

**Comment by stke9** [comment]
Hi, glad you solved this! As a side note, the default dataloader preloads the dataset to RAM to save time during training. This is fine for n phase images stored as ints, but is quite memory hungry for colour images. If the problem persists, you might want to write a dataloader that generates one batch at a time.
